run:
  timeout: 5m
  modules-download-mode: readonly

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: regard
  govet:
    check-shadowing: true
  misspell:
    locale: US
  unused:
    check-exported: false

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - ineffassign
    - misspell
    - unused
    - errcheck
    - gosimple
    - staticcheck
    - typecheck
    - deadcode
    - varcheck
    - structcheck
  disable:
    - funlen
    - gocognit
    - gocyclo
    - lll

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec