run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - unparam
    - nolintlint
    - gocritic
    - gosimple
    - typecheck
    
linters-settings:
  govet:
    enable:
      - shadow
  misspell:
    locale: US
  gocritic:
    disabled-checks:
      - ifElseChain  # Too opinionated
      
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
