name: Release

on:
  push:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    permissions:
      contents: write
      packages: write

    outputs:
      version: ${{ steps.version.outputs.version }}
      created: ${{ steps.version.outputs.created }}

    steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Generate version number
      id: version
      run: |
        # Get the latest tag, default to 0 if no tags exist
        LATEST_TAG=$(git tag -l --sort=-version:refname | head -n1 || echo "0")
        if [ -z "$LATEST_TAG" ] || [ "$LATEST_TAG" = "0" ]; then
          NEW_VERSION="1"
        else
          NEW_VERSION=$((LATEST_TAG + 1))
        fi
        echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT
        echo "created=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
        echo "New version: $NEW_VERSION"

    - name: Create and push tag
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git tag ${{ steps.version.outputs.version }}
        git push origin ${{ steps.version.outputs.version }}

  docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: release
    
    permissions:
      contents: read
      packages: write

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=raw,value=${{ needs.release.outputs.version }}
          type=raw,value=latest

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  build-binaries:
    name: Build Release Binaries
    runs-on: ubuntu-latest
    needs: release
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.24.x

    - name: Build binary
      run: |
        mkdir -p dist

        # Set output filename
        OUTPUT_NAME="regard-${{ matrix.goos }}-${{ matrix.goarch }}"
        if [ "${{ matrix.goos }}" = "windows" ]; then
          OUTPUT_NAME="${OUTPUT_NAME}.exe"
        fi
        
        echo "Building for ${{ matrix.goos }}/${{ matrix.goarch }} -> ${OUTPUT_NAME}"
        
        GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build \
          -ldflags "-s -w -X main.version=${{ needs.release.outputs.version }}" \
          -o "dist/${OUTPUT_NAME}" \
          cmd/regard/main.go
        
        # Verify binary was created
        if [ ! -f "dist/${OUTPUT_NAME}" ]; then
          echo "Failed to build ${OUTPUT_NAME}"
          exit 1
        fi
        
        # Display what we built
        echo "Successfully built:"
        ls -la "dist/${OUTPUT_NAME}"

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: binary-${{ matrix.goos }}-${{ matrix.goarch }}
        path: dist/
        retention-days: 1

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [release, docker, build-binaries]

    permissions:
      contents: write

    steps:
    - name: Download all build artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: binary-*
        path: artifacts/
        merge-multiple: true

    - name: Prepare release assets
      run: |
        mkdir -p dist
        # Copy all binaries to dist/ and create checksums
        find artifacts/ -name "regard-*" -type f -exec cp {} dist/ \;
        sha256sum dist/* > dist/checksums.txt

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ needs.release.outputs.version }}
        name: ${{ needs.release.outputs.version }}
        body: |
          ### Docker
          ```bash
          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.release.outputs.version }}
          ```
          ## Docker Images
          - `${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.release.outputs.version }}`
          - `${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest`
        files: |
          dist/*
        draft: false
        prerelease: false
